export const label = {
    login:"Login",
    submitLogin:"Submit",
    enterEmail:"Enter Email",
    enterPassword:"Enter Password",
    homeScreenTitle:"Rental House",
    Tenant:"Tenant",
    House:"House",
    Report:"Report",
    Profile:"Profile",
    CreateTenant:"CreateTenant",
    tenantName:"Tenant Name",
    tenantPhoneNo:"Tenant Phone No",
    tenantAddress:"Tenant Address",
    tenantIdCardType:"Tenant Id Card Type",
    cardNo:"Card No",
    dateOfOccupy:"Date of occupy",
    houseNo:"House No",
    rent:"Rent",
    advance:"Advance",
    address:"Address",
    nameOfBuilding:"Name Of Building",
    status:"Status",
    CreateHouse:"Create House",
    payment:"Payment",
    settlement:"Settlement",
    rentOfMonth:"Rent of month",
    paidBy:"Paid by",
    paymentMode:"Payment Mode",
    amount:"Amount",
    date:"Date",
    payment:"Payment",
    deduction:"Deduction",
    reason:"Reason",
    returnAmount:"Return Amount",
    Settlement:"Settlement",
    receivedBy:"Received By"
};
